<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfr</string>
	</array>
	<key>name</key>
	<string>Clafer</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*(?!#)</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.clafer</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.clafer</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.clafer</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+)\b</string>
			<key>name</key>
			<string>constant.numeric.clafer</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(clafer|this|parent|dref|root|children|int|integer|string|double|real|maximize|minimize|max|min|sum|product|xor|in|if|then|else|no|not|some|one|all|disj|opt|mux|or|lone|abstract|enum|assert|final|initial|let|never|sometime|lonce|once|always|must|precede|follow|initially|finally|U|until|W|weakuntil|F|eventually|G|globally|X|next|before|after|between|and|until)\b</string>
			<key>name</key>
			<string>keyword.control.clafer</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(#|\?|\*|\+|-&gt;|-&gt;&gt;|\:|\+|-|/|%|\.|&lt;:|:&gt;|\\|\&amp;\&amp;|\|\||,|\+\+|\*\*|--|=|:=|!=|&gt;=|&lt;=|=&gt;|&lt;=&gt;|&lt;|&gt;|(|)|[|]|\.\.|&gt;&gt;|&lt;&lt;|--&gt;|--&gt;&gt;|-[|]-&gt;|]-&gt;&gt;)</string>
			<key>name</key>
			<string>keyword.operator.clafer</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.clafer</string>
	<key>uuid</key>
	<string>47176018-fe13-4440-b721-6972621716be</string>
</dict>
</plist>
